ServiceHost = "0.0.0.0"
ServicePort = 8080

[MinioConfig]
Endpoint = "localhost:9000"
AccessKeyID = "minio"
SecretAccessKey = "minio124"
UseSSL = false
BucketName = "lb1"

[JWT]
token = "supersecretkey"
expires_in = "24h"
signing_method = "HS256"


[Redis]
DialTimeout = "10s"
ReadTimeout = "10s"